# Generated by Django 5.2.4 on 2025-10-31 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_compra', models.DateField(verbose_name='Data da Compra')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('preço', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('largura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Largura')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura')),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Profundidade')),
                ('imagen', models.ImageField(upload_to='produtos/', verbose_name='Imagem')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.compra')),
            ],
        ),
    ]
