# Generated by Django 5.2.4 on 2025-11-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='produtos/', verbose_name='Imagem'),
        ),
    ]
