# Generated by Django 5.2.4 on 2025-11-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_produto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagen',
        ),
    ]
